// <auto-generated />
namespace easycontrol.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ALTER_TABLE_INADIMPLENCIA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_TABLE_INADIMPLENCIA));
        
        string IMigrationMetadata.Id
        {
            get { return "202002231805403_ALTER_TABLE_INADIMPLENCIA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
